#James Script Set 2.2a - Question 9 (ChemLabs)
library(lpSolveAPI)
jamesChemLabs=make.lp(6,2)
set.column(jamesChemLabs, 1, c(1,1,0,0,0.5,0.6))
set.column(jamesChemLabs, 2, c(0,0,1,1,0.5,0.4))
set.constr.type(jamesChemLabs, c(">=","<=",">=","<=","<=","<="))
set.rhs(jamesChemLabs, c(30,150,40,200,150,145))
set.objfn(jamesChemLabs, c(8,10))
lp.control(jamesChemLabs,sense='max')
jamesChemLabs
solve(jamesChemLabs)
get.objective(jamesChemLabs)
get.variables(jamesChemLabs)
plot(jamesChemLabs)
get.sensitivity.rhs(jamesChemLabs)