#James Script Set 2.2a - Question 12 (Wild West)
library(lpSolveAPI)
jamesWildWest=make.lp(3,2)
set.column(jamesWildWest, 1, c(2,1,0))
set.column(jamesWildWest, 2, c(1,0,1))
set.constr.type(jamesWildWest, c("<=","<=","<="))
set.rhs(jamesWildWest, c(400,150,200))
set.objfn(jamesWildWest, c(8,5))
lp.control(jamesWildWest,sense='max')
jamesWildWest
solve(jamesWildWest)
get.objective(jamesWildWest)
get.variables(jamesWildWest)
plot(jamesWildWest)
get.sensitivity.rhs(jamesWildWest)