#James Script Minimization Model 2.2B - Question 4 (John)
library(lpSolveAPI)
jamesJohn=make.lp(5,2)
set.column(jamesJohn, 1, c(1,1,1,0,0))
set.column(jamesJohn, 2, c(1,0,0,1,1))
set.constr.type(jamesJohn, c(">=",">=","<=",">=","<="))
set.rhs(jamesJohn, c(20,5,12,6,10))
set.objfn(jamesJohn, c(8,6))
jamesJohn
solve(jamesJohn)
get.objective(jamesJohn)
get.variables(jamesJohn)
plot(jamesJohn)
get.sensitivity.rhs(jamesJohn)