#James Script Set 2.2a - Question 13 (Show and Sell)
library(lpSolveAPI)
jamesShowSell=make.lp(3,2)
set.column(jamesShowSell, 1, c(15,-1,1))
set.column(jamesShowSell, 2, c(300,2,0))
set.constr.type(jamesShowSell,c("<=","<=","<="))
set.rhs(jamesShowSell, c(10000,0,400))
set.objfn(jamesShowSell, c(1,25))
lp.control(jamesShowSell,sense='max')
jamesShowSell
solve(jamesShowSell)
get.objective(jamesShowSell)
get.variables(jamesShowSell)
plot(jamesShowSell)
get.sensitivity.rhs(jamesShowSell)