#James Script Set 2.2a Question 6 (Alumco)
library(lpSolveAPI)
jamesAlumco = make.lp(3,2)
set.column(jamesAlumco, 1, c(1/800,1,0))
set.column(jamesAlumco, 2, c(1/600,0,1))
set.constr.type(jamesAlumco, c("<=","<-","<="))
set.rhs(jamesAlumco, c(1,550,580))
set.objfn(jamesAlumco, c(40,35))
lp.control(jamesAlumco,sense='max')
jamesAlumco
solve(jamesAlumco)
get.objective(jamesAlumco)
get.variables(jamesAlumco)
plot(jamesAlumco)
get.sensitivity.rhs(jamesAlumco)
